version: "3.8"

services:

  luacov-sonarcloud:
    build:
      context: .
    stdin_open: true
    volumes:
      - ./:/home/luacov-sonarcloud
    ports:
      - "8001:8001"
      - "8000:8000"
    entrypoint: /bin/bash
